# Generated by Django 6.0.1 on 2026-01-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='loyalty_points',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='store_branch',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerpreference',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerpreference',
            name='category',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='accounts_cu_email_cc1dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['city', 'store_branch'], name='accounts_cu_city_828ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['-created_at'], name='accounts_cu_created_21da3e_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpreference',
            index=models.Index(fields=['customer', 'category'], name='accounts_cu_custome_7631af_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpreference',
            index=models.Index(fields=['-preference_score'], name='accounts_cu_prefere_6dc99a_idx'),
        ),
    ]
