# Generated by Django 6.0.1 on 2026-01-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cashback_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='orders_over_minimum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_cashback_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
