# Generated by Django 6.0.1 on 2026-01-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.IntegerField(blank=True, help_text='Calories per 100g', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='carbon_footprint',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='CO2 kg per unit', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='carbs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Carbohydrates (g) per 100g', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='eco_score',
            field=models.IntegerField(blank=True, help_text='Eco-friendliness score 1-100', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fat (g) per 100g', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fiber',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fiber (g) per 100g', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='market_avg_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average market price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Protein (g) per 100g', max_digits=5, null=True),
        ),
    ]
