# Generated by Django 6.0.1 on 2026-01-23 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('loyalty_card', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kiosk_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kiosk Session',
                'verbose_name_plural': 'Kiosk Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='KioskInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('product_view', 'Product View'), ('product_search', 'Product Search'), ('recommendation_view', 'Recommendation View'), ('location_lookup', 'Location Lookup'), ('promotion_view', 'Promotion View')], max_length=50)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('search_query', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='kiosk.kiosksession')),
            ],
            options={
                'verbose_name': 'Kiosk Interaction',
                'verbose_name_plural': 'Kiosk Interactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
